version: "3.9"

services:
  streamlit_app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - LOCAL=false

  azure_function:
    build:
      context: ./azure_function
      dockerfile: Dockerfile
    ports:
      - "7071:7071"
    environment:
      - LOCAL=true

