stages:
  ðŸ§ _train_model:
    cmd: >
      papermill notebooks/training.ipynb _
      -p metadata_path ${model.metadata_path} 
      -p clicks_path ${model.clicks_path}
      -p output_path ${model.output_path}
    deps:
      - data/deps/clicks_sample.csv
      - data/deps/articles_metadata.csv
    outs:
      - data/outs/model/model_svd.pkl

  â˜ï¸_upload_model:
    cmd: >
      azcopy copy data/outs/model/model_svd.pkl "$MODEL_SAS_URL" --overwrite=true
    deps:
      - data/outs/model/model_svd.pkl

  ðŸš€_deploy_function:
    cmd: >
      cd azure_function &&
      func azure functionapp publish "$AZURE_FUNCTION_NAME" --python
    deps:
      - azure_function/

  ðŸŽ¨_Deploy_Streamlit_App:
    cmd: >
      echo "Streamlit deployment logic goes here"
#    deps:
#      - streamlit_app/

#  ðŸ”_Inject MODEL_SAS_URL in Azure Function config
#     cmd: >
#       az functionapp config appsettings set \
#         --name "$AZURE_FUNCTION_NAME" \
#         --resource-group "$AZURE_RESOURCE_GROUP" \
#         --settings 'MODEL_SAS_URL='"$MODEL_SAS_URL"