stages:
  🧠_train_model:
    cmd: >
      papermill notebooks/training.ipynb _
      -p metadata_path ${model.metadata_path} 
      -p clicks_path ${model.clicks_path}
      -p output_path ${model.output_path}
    deps:
      - data/deps/clicks_sample.csv
      - data/deps/articles_metadata.csv
    outs:
      - data/outs/model/model_svd.pkl

  ☁️_upload_model:
    cmd: ./scripts/upload_model.sh
    deps:
      - data/outs/model/model_svd.pkl
      - scripts/upload_model.sh

  🚀_deploy_function:
    cmd: ./scripts/deploy_function.sh
    deps:
      - azure_function/
      - scripts/deploy_function.sh

  🎨_Deploy_Streamlit_App:
    cmd: ./scripts/deploy_streamlit.sh
    deps:
      - scripts/deploy_streamlit.sh

#  🔐_Inject MODEL_SAS_URL in Azure Function config
#     cmd: >
#       az functionapp config appsettings set \
#         --name "$AZURE_FUNCTION_NAME" \
#         --resource-group "$AZURE_RESOURCE_GROUP" \
#         --settings 'MODEL_SAS_URL='"$MODEL_SAS_URL"
