stages:
  ðŸ§ _train_model:
    cmd: >
      papermill notebooks/training.ipynb _
      -p metadata_path ${model.metadata_path} 
      -p clicks_path ${model.clicks_path}
      -p embeddings_path ${model.embeddings_path}
      -p content_based_model_path ${model.content_based_model_path}
      -p collaborative_model_path ${model.collaborative_model_path}
    deps:
      - data/deps/clicks_sample.csv
      - data/deps/articles_metadata.csv
      - data/deps/articles_embeddings.pickle
    outs:
      - data/outs/model/content_based_model.pkl
      - data/outs/model/collaborative_filtering_svd.pkl

  â˜ï¸_upload_content_based_model:
    cmd: ./scripts/upload_model.sh content_based_model.pkl
    deps:
      - data/outs/model/content_based_model.pkl
      - scripts/upload_model.sh

  â˜ï¸_upload_collaborative_filtering_model:
    cmd: ./scripts/upload_model.sh collaborative_filtering_svd.pkl
    deps:
      - data/outs/model/collaborative_filtering_svd.pkl
      - scripts/upload_model.sh

  ðŸš€_deploy_function:
    cmd: ./scripts/deploy_function.sh
    deps:
      - scripts/deploy_function.sh
    always_changed: true

  ðŸŽ¨_Deploy_Streamlit_App:
    cmd: ./scripts/deploy_streamlit.sh
    deps:
      - scripts/deploy_streamlit.sh
    always_changed: true

  ðŸ”_test_streamlit_app:
    cmd: ./scripts/test_streamlit.sh
    deps:
      - scripts/test_streamlit.sh
    always_changed: true

#  ðŸ”_Inject MODEL_SAS_URL in Azure Function config
#     cmd: >
#       az functionapp config appsettings set \
#         --name "$AZURE_FUNCTION_NAME" \
#         --resource-group "$AZURE_RESOURCE_GROUP" \
#         --settings 'MODEL_SAS_URL='"$MODEL_SAS_URL"
