model:
  metadata_path: "data/deps/articles_metadata.csv"
  clicks_path: "data/deps/clicks_sample.csv"
  embeddings_path: "data/deps/articles_embeddings.pickle"
  collaborative_model_path: "data/outs/model/collaborative_filtering_svd.pkl"
  content_based_model_path: "data/outs/model/content_based_model.pkl"
